# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'battery.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 620)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 70, 324, 500))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_14.setFont(font)
        self.doubleSpinBox_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_14.setDecimals(4)
        self.doubleSpinBox_14.setMinimum(-1000.0)
        self.doubleSpinBox_14.setMaximum(10000.0)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout.addWidget(self.doubleSpinBox_14, 15, 1, 1, 1)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_15.setFont(font)
        self.doubleSpinBox_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_15.setDecimals(4)
        self.doubleSpinBox_15.setMinimum(-1000.0)
        self.doubleSpinBox_15.setMaximum(10000.0)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.gridLayout.addWidget(self.doubleSpinBox_15, 16, 1, 1, 1)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_16.setFont(font)
        self.doubleSpinBox_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_16.setDecimals(4)
        self.doubleSpinBox_16.setMinimum(-1000.0)
        self.doubleSpinBox_16.setMaximum(10000.0)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.gridLayout.addWidget(self.doubleSpinBox_16, 17, 1, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_12.setFont(font)
        self.doubleSpinBox_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_12.setDecimals(4)
        self.doubleSpinBox_12.setMinimum(-1000.0)
        self.doubleSpinBox_12.setMaximum(10000.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout.addWidget(self.doubleSpinBox_12, 13, 1, 1, 1)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_17.setFont(font)
        self.doubleSpinBox_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_17.setDecimals(4)
        self.doubleSpinBox_17.setMinimum(-1000.0)
        self.doubleSpinBox_17.setMaximum(10000.0)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.gridLayout.addWidget(self.doubleSpinBox_17, 18, 1, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_13.setFont(font)
        self.doubleSpinBox_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_13.setDecimals(4)
        self.doubleSpinBox_13.setMinimum(-1000.0)
        self.doubleSpinBox_13.setMaximum(10000.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout.addWidget(self.doubleSpinBox_13, 14, 1, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_9.setFont(font)
        self.doubleSpinBox_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_9.setDecimals(4)
        self.doubleSpinBox_9.setMinimum(-1000.0)
        self.doubleSpinBox_9.setMaximum(10000.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout.addWidget(self.doubleSpinBox_9, 10, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 16, 0, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_11.setFont(font)
        self.doubleSpinBox_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_11.setDecimals(4)
        self.doubleSpinBox_11.setMinimum(-1000.0)
        self.doubleSpinBox_11.setMaximum(10000.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout.addWidget(self.doubleSpinBox_11, 12, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 17, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 14, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 15, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 18, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 12, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_4.setDecimals(4)
        self.doubleSpinBox_4.setMaximum(10000.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout.addWidget(self.doubleSpinBox_4, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_8.setFont(font)
        self.doubleSpinBox_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_8.setDecimals(4)
        self.doubleSpinBox_8.setMinimum(-1000.0)
        self.doubleSpinBox_8.setMaximum(10000.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout.addWidget(self.doubleSpinBox_8, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 4, 1, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_6.setFont(font)
        self.doubleSpinBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_6.setDecimals(4)
        self.doubleSpinBox_6.setMaximum(10000.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout.addWidget(self.doubleSpinBox_6, 7, 1, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_7.setFont(font)
        self.doubleSpinBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_7.setDecimals(4)
        self.doubleSpinBox_7.setMaximum(10000.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout.addWidget(self.doubleSpinBox_7, 8, 1, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_5.setFont(font)
        self.doubleSpinBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_5.setDecimals(4)
        self.doubleSpinBox_5.setMaximum(10000.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout.addWidget(self.doubleSpinBox_5, 6, 1, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_3.setDecimals(4)
        self.doubleSpinBox_3.setMaximum(10000.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(4)
        self.doubleSpinBox_2.setMaximum(10000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 11, 1, 1, 1)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_18.setFont(font)
        self.doubleSpinBox_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_18.setDecimals(4)
        self.doubleSpinBox_18.setMinimum(-1000.0)
        self.doubleSpinBox_18.setMaximum(10000.0)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.gridLayout.addWidget(self.doubleSpinBox_18, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(30, 20, 321, 31))
        self.label_18.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.label_18.setObjectName("label_18")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 580, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_15.setText(_translate("Dialog", "Discharge efficiency(%)"))
        self.label_16.setText(_translate("Dialog", "Charge efficiency(%)"))
        self.label_13.setText(_translate("Dialog", "Lifecycle(years)"))
        self.label_14.setText(_translate("Dialog", "Price per kWh installed(USD/kW)"))
        self.label_9.setText(_translate("Dialog", "Battery Voltage (V)"))
        self.label_10.setText(_translate("Dialog", "Inverter efficiency(%)"))
        self.label_12.setText(_translate("Dialog", "Factor initial capital cost invested(%)"))
        self.label_17.setText(_translate("Dialog", "Charge efficiency(%)"))
        self.label_11.setText(_translate("Dialog", "O&Mfactor initial investment(%)"))
        self.label_4.setText(_translate("Dialog", "Maximum depth of discharge(%)"))
        self.label_5.setText(_translate("Dialog", "Maximum number of cycles"))
        self.label_3.setText(_translate("Dialog", "Capacity Rate(h)"))
        self.label_6.setText(_translate("Dialog", "Price per kWh generated(USD/kWh)"))
        self.label_2.setText(_translate("Dialog", "Self-Discharge rate"))
        self.label_7.setText(_translate("Dialog", "Battery cell capacity(kW)"))
        self.label_8.setText(_translate("Dialog", "DC system voltage (V)"))
        self.label.setText(_translate("Dialog", "Positive battery constant"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameters Battery</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

